# Generated by Django 3.2.23 on 2024-11-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='generated_images/'),
        ),
    ]
